### ISSUE TITLE
Installation error:  argument encoding="UTF-8" is ignored in MBCS locales

### ISSUE THREAD

**Issue by CLRafaelR** [vasishth/lingpsych#1]
I have tried both `devtools::install_github("vasishth/lingpsych")`, and the alternative `devtools::install("lingpsych-main")` after downloading and unzipping the archive. However, I got the following errors on the locale setting and on the invalid multibyte character (`invalid multibyte character in parser at line 279`), when I ran `devtools::install_github("vasishth/lingpsych")` and `devtools::install("lingpsych-main")`:

``` r
√  checking for file 'C:\Users\my\path\to\lingpsych-main/DESCRIPTION' (790ms)
-  preparing 'lingpsych': (851ms)
√  checking DESCRIPTION meta-information ... 
-  installing the package to process help pages (432ms)
         -----------------------------------
-  installing *source* package 'lingpsych' ...
   ** using staged installation
   Warning in parse(con, encoding = "UTF-8") :
     argument encoding="UTF-8" is ignored in MBCS locales
   ** R
   ** data
   *** moving datasets to lazyload DB
   Warning in load(zfile, envir = tmp_env) :
     strings not representable in native encoding will be translated to UTF-8
   Warning in load(zfile, envir = tmp_env) :
     strings not representable in native encoding will be translated to UTF-8
   Warning in load(zfile, envir = tmp_env) :
     strings not representable in native encoding will be translated to UTF-8
   Warning in load(zfile, envir = tmp_env) :
     strings not representable in native encoding will be translated to UTF-8
   ** inst
   ** byte-compile and prepare package for lazy loading
   ** help
   Warning in parse(n = -1, file = file, srcfile = NULL, keep.source = FALSE,  :
     argument encoding="UTF-8" is ignored in MBCS locales
   Error :  invalid multibyte character in parser at line 279
   ERROR: installing Rd objects failed for package 'lingpsych'
-  removing 'C:/Users/my/path/to/AppData/Local/Temp/Rtmp4Wz9qN/Rinst28b43d3033d0/lingpsych'
         -----------------------------------
   ERROR: package installation failed
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ** inst
E> ** byte-compile and prepare package for lazy loading
E> ** help
E> Warning in parse(n = -1, file = file, srcfile = NULL, keep.source = FALSE,  :
E>   argument encoding="UTF-8" is ignored in MBCS locales
E> Error :  invalid multibyte character in parser at line 279
E> ERROR: installing Rd objects failed for package 'lingpsych'
E> * removing 'C:/Users/my/path/to/AppData/Local/Temp/Rtmp4Wz9qN/Rinst28b43d3033d0/lingpsych'
E>       -----------------------------------
E> ERROR: package installation failed
Type .Last.error.trace to see where the error occurred
```

I run R 4.1.0 under the following environment. I also have rtools40.

``` r
> Sys.info()[c("sysname", "release", "version", "machine")]
      sysname       release       version       machine 
    "Windows"      "10 x64" "build 19042"      "x86-64" 
```

Is there anything I can do to solve the issue?

**Comment by CLRafaelR** [comment]
Somehow I succeeded in installing the previous version [ee1c38f](https://github.com/vasishth/lingpsych/commit/ee1c38fc744cccd2ebcb1693b3fd9961411028d8):

``` r
> devtools::install_github("vasishth/lingpsych@ee1c38f")

Downloading GitHub repo vasishth/lingpsych@ee1c38f
√  checking for file 'C:\Users\my\path\AppData\Local\Temp\Rtmp2xl0I9\remotes42142f574b0\vasishth-lingpsych-ee1c38f/DESCRIPTION' (389ms)
-  preparing 'lingpsych':
√  checking DESCRIPTION meta-information ... 
-  installing the package to process help pages
   Warning in get_bibentries(package = package, ..., stop_on_error = FALSE) :
     Couldn't find file REFERENCES.bib in package `lingpsych'
   Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
     possibly non-existing or duplicated key(s) in bib file from package 'lingpsych':
       johnson2011quantitative
   
   Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
     possibly non-existing or duplicated key(s) in bib file from package 'lingpsych':
       johnson2011quantitative
   
   Loading required namespace: lingpsych
   Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
     possibly non-existing or duplicated key(s) in bib file from package 'lingpsych':
       DillonEtAl2013
   
   Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
     possibly non-existing or duplicated key(s) in bib file from package 'lingpsych':
       DillonEtAl2013
   
   Warning in get_bibentries(package = package, ..., stop_on_error = FALSE) :
     Couldn't find file REFERENCES.bib in package `bcogsci'
   Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
     possibly non-existing or duplicated key(s) in bib file from package 'bcogsci':
       AnnaLphd
   
   Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
     possibly non-existing or duplicated key(s) in bib file from package 'bcogsci':
       AnnaLphd
   
   Loading required namespace: bcogsci
   Failed with error:  'there is no package called 'bcogsci''
   Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
     possibly non-existing or duplicated key(s) in bib file from package 'lingpsych':
       FrankEtAl2015
   
   Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
     possibly non-existing or duplicated key(s) in bib file from package 'lingpsych':
       FrankEtAl2015
   
   Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
     possibly non-existing or duplicated key(s) in bib file from package 'lingpsych':
       VSLK08
   
   Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
     possibly non-existing or duplicated key(s) in bib file from package 'lingpsych':
       VSLK08
   
   Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
     possibly non-existing or duplicated key(s) in bib file from package 'lingpsych':
       grodner
   
   Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
     possibly non-existing or duplicated key(s) in bib file from package 'lingpsych':
       grodner
   
   Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
     possibly non-existing or duplicated key(s) in bib file from package 'lingpsych':
       grodner
   
   Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
     possibly non-existing or duplicated key(s) in bib file from package 'lingpsych':
       grodner
   
   Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
     possibly non-existing or duplicated key(s) in bib file from package 'lingpsych':
       gibsonwu
   
   Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
     possibly non-existing or duplicated key(s) in bib file from package 'lingpsych':
       gibsonwu
   
   Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
     possibly non-existing or duplicated key(s) in bib file from package 'lingpsych':
       VasishthetalPLoSOne2013
   
   Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
     possibly non-existing or duplicated key(s) in bib file from package 'lingpsych':
       gibsonwu
   
   Warning in safe_cite(keys, bibs, textual = textual, before = before, after = after,  :
     possibly non-existing or duplicated key(s) in bib file from package 'lingpsych':
       VasishthetalPLoSOne2013
   
-  saving partial Rd database
   Warning in parse(con, encoding = "UTF-8") :
     argument encoding="UTF-8" is ignored in MBCS locales
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in
     serialize/load version 3 cannot be read in older versions of R.
     File(s) containing such objects:
       'lingpsych/data/df_F1data.rda' 'lingpsych/data/df_dillonE1.rda'
       'lingpsych/data/df_discreteagrmt.rda' 'lingpsych/data/df_dutch.rda'
       'lingpsych/data/df_english.rda' 'lingpsych/data/df_gg05e1.rda'
       'lingpsych/data/df_gg05e1_full.rda' 'lingpsych/data/df_gibsonwu.rda'
       'lingpsych/data/df_gibsonwu2.rda'
-  building 'lingpsych_0.0.0.9000.tar.gz'
   
Installing package into ‘C:/Users/my/path/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package 'lingpsych' ...
** using staged installation
Warning in parse(con, encoding = "UTF-8") :
  argument encoding="UTF-8" is ignored in MBCS locales
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'lingpsych'
    finding HTML links ... done
    df_F1data                               html  
    df_dillonE1                             html  
    df_discreteagrmt                        html  
    df_dutch                                html  
    df_english                              html  
    df_gg05e1                               html  
    df_gg05e1_full                          html  
    df_gibsonwu                             html  
    df_gibsonwu2                            html  
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (lingpsych)
```

However, I found that it was the version [ba333ee](https://github.com/vasishth/lingpsych/commit/ba333ee2a814b5a73795c091d0ea1ab6e0530687) and its successors that I failed to install. When I tried to install Ver.  [ba333ee](https://github.com/vasishth/lingpsych/commit/ba333ee2a814b5a73795c091d0ea1ab6e0530687), the error message said there is an `invalid multibyte character in parser at line 180`. The difference between Ver [ee1c38f](https://github.com/vasishth/lingpsych/commit/ee1c38fc744cccd2ebcb1693b3fd9961411028d8), which I managed to install, and Ver [ba333ee](https://github.com/vasishth/lingpsych/commit/ba333ee2a814b5a73795c091d0ea1ab6e0530687), which I started to fail to install, is the `REFERENCE.bib`. [l.180 of `REFERENCE.bib`](https://github.com/vasishth/lingpsych/commit/ba333ee2a814b5a73795c091d0ea1ab6e0530687#diff-bedc36f49f62d234a2c4f1b616722e977766a9bc32f1d11aec4cf186d083cc76R180) is the same line that the error message [I posted earlier](https://github.com/vasishth/lingpsych/issues/1#issue-992868092) said had a multibyte character, [l. 279](https://github.com/vasishth/lingpsych/blob/92060c6a6abe4dfe4f13a8b7ad8ea23c2ec17743/inst/REFERENCES.bib#L279-L280). I could not find multibyte issue around here, but would you check around the line?

``` r
> devtools::install_github("vasishth/lingpsych@ba333ee")
Downloading GitHub repo vasishth/lingpsych@ba333ee
√  checking for file 'C:\Users\my\path\AppData\Local\Temp\RtmpaUqhDL\remotes391c5705434d\vasishth-lingpsych-ba333ee/DESCRIPTION' (418ms)
-  preparing 'lingpsych':
√  checking DESCRIPTION meta-information ... 
-  installing the package to process help pages
         -----------------------------------
-  installing *source* package 'lingpsych' ...
   ** using staged installation
   Warning in parse(con, encoding = "UTF-8") :
     argument encoding="UTF-8" is ignored in MBCS locales
   ** R
   ** data
   *** moving datasets to lazyload DB
   ** inst
   ** byte-compile and prepare package for lazy loading
   ** help
   Warning in parse(n = -1, file = file, srcfile = NULL, keep.source = FALSE,  :
     argument encoding="UTF-8" is ignored in MBCS locales
   Error :  invalid multibyte character in parser at line 180
   ERROR: installing Rd objects failed for package 'lingpsych'
-  removing 'C:/Users/my/path/AppData/Local/Temp/RtmpYVuU1x/Rinst28e42bc3443f/lingpsych'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'lingpsych' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ** inst
E> ** byte-compile and prepare package for lazy loading
E> ** help
E> Warning in parse(n = -1, file = file, srcfile = NULL, keep.source = FALSE,  :
E>   argument encoding="UTF-8" is ignored in MBCS locales
E> Error :  invalid multibyte character in parser at line 180
E> ERROR: installing Rd objects failed for package 'lingpsych'
E> * removing 'C:/Users/my/path/AppData/Local/Temp/RtmpYVuU1x/Rinst28e42bc3443f/lingpsych'
E>       -----------------------------------
E> ERROR: package installation failed
```

**Comment by vasishth** [comment]
ごめんなさい。これは私の間違いでした。もう一回試してみてください。lingpsychを無視して、bcogsciだけをインストールしてみてください。

**Comment by CLRafaelR** [comment]
Thank you for your response. Actually, the installation of `bcogsci` fails with the similar error which I posted earlier:

``` r
> devtools::install_github("bnicenboim/bcogsci")
Downloading GitHub repo bnicenboim/bcogsci@HEAD
√  checking for file 'C:\Users\my\path\AppData\Local\Temp\RtmpC4sOda\remotes4ee45789217a\bnicenboim-bcogsci-7f400af/DESCRIPTION' (359ms)
-  preparing 'bcogsci': (766ms)
√  checking DESCRIPTION meta-information ... 
-  installing the package to process help pages (524ms)
         -----------------------------------
-  installing *source* package 'bcogsci' ...
   ** using staged installation
   ** R
   ** data
   *** moving datasets to lazyload DB
   ** inst
   ** byte-compile and prepare package for lazy loading
   ** help
   Warning in parse(n = -1, file = file, srcfile = NULL, keep.source = FALSE,  :
     argument encoding="UTF-8" is ignored in MBCS locales
   Error :  invalid multibyte character in parser at line 116
   ERROR: installing Rd objects failed for package 'bcogsci'
-  removing 'C:/Users/my/path/AppData/Local/Temp/RtmpwL8ZqG/Rinst50646daa88e/bcogsci'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'bcogsci' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ** inst
E> ** byte-compile and prepare package for lazy loading
E> ** help
E> Warning in parse(n = -1, file = file, srcfile = NULL, keep.source = FALSE,  :
E>   argument encoding="UTF-8" is ignored in MBCS locales
E> Error :  invalid multibyte character in parser at line 116
E> ERROR: installing Rd objects failed for package 'bcogsci'
E> * removing 'C:/Users/my/path/AppData/Local/Temp/RtmpwL8ZqG/Rinst50646daa88e/bcogsci'
E>       -----------------------------------
E> ERROR: package installation failed
```

I think this issue should be reported and discussed in `bcogsci` repo, but I post the issue here, too, for the record.

**Comment by vasishth** [comment]
I am able to install it fine on my computer (macOS running Big Sur, M1 chip):


> devtools::install_github("bnicenboim/bcogsci",force=TRUE)
Downloading GitHub repo bnicenboim/bcogsci@HEAD
✓  checking for file ‘/private/var/folders/1f/k1sq7jzx7hxcbs02r6l712mh0000gn/T/RtmpVO86rp/remotes6db361ad3004/bnicenboim-bcogsci-c2bf813/DESCRIPTION’ ...
─  preparing ‘bcogsci’:
✓  checking DESCRIPTION meta-information ...
─  installing the package to process help pages
   Loading required namespace: bcogsci
─  saving partial Rd database (609ms)
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in
     serialize/load version 3 cannot be read in older versions of R.
     File(s) containing such objects:
       ‘bcogsci/data/df_VMJG18E1.rda’ ‘bcogsci/data/df_VMJG18E2.rda’
       ‘bcogsci/data/df_VMJG18E3.rda’ ‘bcogsci/data/df_VMJG18E4.rda’
       ‘bcogsci/data/df_VMJG18E5.rda’ ‘bcogsci/data/df_VMJG18E6.rda’
       ‘bcogsci/data/df_VMJG18E7.rda’ ‘bcogsci/data/df_VOTenglish.rda’
       ‘bcogsci/data/df_VOTmandarin.rda’ ‘bcogsci/data/df_buerki.rda’
       ‘bcogsci/data/df_chineseRCs.rda’ ‘bcogsci/data/df_dillonE1.rda’
       ‘bcogsci/data/df_dillonrep.rda’ ‘bcogsci/data/df_discreteagrmt.rda’
       ‘bcogsci/data/df_dutch.rda’ ‘bcogsci/data/df_english.rda’
       ‘bcogsci/data/df_gibsonwu.rda’ ‘bcogsci/data/df_gibsonwu2.rda’
       ‘bcogsci/data/df_persianE1.rda’ ‘bcogsci/data/df_polarity.rda’
       ‘bcogsci/data/df_powerpose.rda’ ‘bcogsci/data/df_red.rda’
       ‘bcogsci/data/df_smithE1.rda’ ‘bcogsci/data/df_smithE2.rda’
       ‘bcogsci/data/df_swets08.rda’
─  building ‘bcogsci_0.0.0.9000.tar.gz’
   
* installing *source* package ‘bcogsci’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (bcogsci)

**Comment by vasishth** [comment]
I just tested this on my Win7 machine. I can install the package fine. See below. So I can't reproduce your error, sorry. 

> devtools::install_github("bnicenboim/bcogsci")
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 4.0.2 was found. (Only the following incompatible version(s) of Rtools were found:3.5)

Please download and install Rtools 4.0 from https://cran.r-project.org/bin/windows/Rtools/.
Downloading GitHub repo bnicenboim/bcogsci@HEAD
Installing 2 packages: rbibutils, Rdpack
Installing packages into ‘C:/Users/vasis/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/rbibutils_2.2.3.zip'
Content type 'application/zip' length 1123368 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/Rdpack_2.1.2.zip'
Content type 'application/zip' length 921662 bytes (900 KB)
downloaded 900 KB

package ‘rbibutils’ successfully unpacked and MD5 sums checked
package ‘Rdpack’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\vasis\AppData\Local\Temp\RtmpO2YegV\downloaded_packages
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 4.0.2 was found. (Only the following incompatible version(s) of Rtools were found:3.5)

Please download and install Rtools 4.0 from https://cran.r-project.org/bin/windows/Rtools/.
√  checking for file 'C:\Users\vasis\AppData\Local\Temp\RtmpO2YegV\remotes47243df845cd\bnicenboim-bcogsci-c2bf813/DESCRIPTION' ...
-  preparing 'bcogsci':
√  checking DESCRIPTION meta-information ... 
-  installing the package to process help pages
   Loading required namespace: bcogsci
-  saving partial Rd database (1.4s)
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'bcogsci/data/df_VMJG18E1.rda'  'bcogsci/data/df_VMJG18E2.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'bcogsci/data/df_VMJG18E3.rda'  'bcogsci/data/df_VMJG18E4.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'bcogsci/data/df_VMJG18E5.rda'  'bcogsci/data/df_VMJG18E6.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'bcogsci/data/df_VMJG18E7.rda'  'bcogsci/data/df_VOTenglish.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'bcogsci/data/df_VOTmandarin.rda'  'bcogsci/data/df_buerki.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'bcogsci/data/df_chineseRCs.rda'  'bcogsci/data/df_dillonE1.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'bcogsci/data/df_dillonrep.rda'  'bcogsci/data/df_discreteagrmt.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'bcogsci/data/df_dutch.rda'  'bcogsci/data/df_english.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'bcogsci/data/df_gibsonwu.rda'  'bcogsci/data/df_gibsonwu2.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'bcogsci/data/df_persianE1.rda'  'bcogsci/data/df_polarity.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'bcogsci/data/df_powerpose.rda'  'bcogsci/data/df_red.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'bcogsci/data/df_smithE1.rda'  'bcogsci/data/df_smithE2.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'bcogsci/data/df_swets08.rda'
-  building 'bcogsci_0.0.0.9000.tar.gz'
   
Installing package into ‘C:/Users/vasis/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'bcogsci' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'bcogsci'
    finding HTML links ... done
    bcogsci-package                         html  
    df_BF                                   html  
    df_VMJG18E1                             html  
    df_VMJG18E2                             html  
    df_VMJG18E3                             html  
    df_VMJG18E4                             html  
    df_VMJG18E5                             html  
    df_VMJG18E6                             html  
    df_VMJG18E7                             html  
    df_VOTenglish                           html  
    df_VOTmandarin                          html  
    df_ab                                   html  
    df_ab_complete                          html  
    df_buerki                               html  
    df_chineseRCs                           html  
    df_contrasts1                           html  
    df_contrasts2                           html  
    df_contrasts3                           html  
    df_contrasts4                           html  
    df_contrasts5                           html  
    df_contrasts6                           html  
    df_contrasts7                           html  
    df_dillonE1                             html  
    df_dillonrep                            html  
    df_discreteagrmt                        html  
    df_dots                                 html  
    df_dutch                                html  
    df_eeg                                  html  
    df_eeg_complete                         html  
    df_english                              html  
    df_fallacy                              html  
    df_gg05_complete                        html  
    df_gg05_rc                              html  
    df_gibsonwu                             html  
    df_gibsonwu2                            html  
    df_persianE1                            html  
    df_polarity                             html  
    df_powerpose                            html  
    df_pupil                                html  
    df_pupil_complete                       html  
    df_pupil_pilot                          html  
    df_recall                               html  
    df_recall_complete                      html  
    df_red                                  html  
    df_sbi                                  html  
    df_sbi_complete                         html  
    df_schizophrenia                        html  
    df_smithE1                              html  
    df_smithE2                              html  
    df_source_monitoring                    html  
    df_spacebar                             html  
    df_stroop                               html  
    df_stroop_complete                      html  
    df_swets08                              html  
    stan-binomial_cloze                     html  
    stan-normal                             html  
    stan-normal2                            html  
    stan-pupil_gen                          html  
    stan-pupil_model                        html  
    stan-rema                               html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (bcogsci)

**Comment by vasishth** [comment]
I will try to figure out where the mistake is coming from. maybe I have chinese characters in my chinese data. i will try removing them and then things might work.

**Comment by CLRafaelR** [comment]
@vasishth 

Although I do not the reason, I successfully installed the current version of `lingpsych` and `bcogsci` to R 4.2.0! Now the issues is resolved and therefore I close this thread.

```r
> sessionInfo()
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=Japanese_Japan.utf8  LC_CTYPE=Japanese_Japan.utf8
[3] LC_MONETARY=Japanese_Japan.utf8 LC_NUMERIC=C
[5] LC_TIME=Japanese_Japan.utf8
```

**Comment by vasishth** [comment]
thanks for letting us know!
